tickets:
    resource: "@TicketsBundle/Resources/config/routing.yml"
    prefix:   /

application_gillbus_tickets:
    resource: "@TicketsBundle/Resources/config/routing.yml"
    prefix:   /tch

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#
# Support for LiipImagineBundle
#_imagine:
#    resource: .
#    type:     imagine

#_front:
#    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /

_api:
    resource: routing_api.yml
    prefix:   /api



