services:
#    application_gillbus_etravels.example:
#        class: Application\Gillbus\EtravelsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    application_gillbus_etravelsPages.admin.etravelsPages:
        class: Application\Gillbus\EtravelsPagesBundle\Admin\EtravelsPagesAdmin
        arguments: [~, Application\Gillbus\EtravelsPagesBundle\Entity\Pages, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Etravels Pages}

