services:
#    tickets.example:
#        class: Application\Gillbus\TicketsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    application_gillbus_tickets.admin.blogpost:
        class : Application\Gillbus\TicketsBundle\Admin\BlogPostAdmin
        arguments:
            - ~
            - Application\Gillbus\TicketsBundle\Entity\BlogPost
            - SonataAdminBundle:CRUD
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Blog Posts}
        calls:
            - [ setTemplate, [edit, TicketsBundle:BlogAdmin:Post/edit.html.twig]]

    application_gillbus_tickets.admin.blogcategory:
        class: Application\Gillbus\TicketsBundle\Admin\BlogCategoryAdmin
        arguments:
            - ~
            - Application\Gillbus\TicketsBundle\Entity\BlogCategory
            - SonataAdminBundle:CRUD
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Blog Category}
        calls:
            - [ setTemplate, [edit, TicketsBundle:BlogAdmin:Category/edit.html.twig]]